""" A nice place to hold all the constants """

DEBUG = False

CPU_NICE = 0.03
SIM_RATE = 0.255

# status (right side) screen constants, modify the top to modify the rest
STATUS_SCREEN_SIM_TALLY_HEADER_V_ALIGN = 1
STATUS_SCREEN_SIM_TALLY_V_ALIGN =  STATUS_SCREEN_SIM_TALLY_HEADER_V_ALIGN + 1
STATUS_SCREEN_VIM_KEYMAP_V_ALIGN = STATUS_SCREEN_SIM_TALLY_V_ALIGN + 3
STATUS_SCREEN_DIR_KEYMAP_V_ALIGN = STATUS_SCREEN_SIM_TALLY_V_ALIGN + 4
STATUS_SCREEN_PAUSE_V_ALIGN = STATUS_SCREEN_SIM_TALLY_V_ALIGN + 5
STATUS_SCREEN_FILL_V_ALIGN = STATUS_SCREEN_SIM_TALLY_V_ALIGN + 6
STATUS_SCREEN_TOGGLE_V_ALIGN = STATUS_SCREEN_SIM_TALLY_V_ALIGN + 7
STATUS_SCREEN_CLEAR_V_ALIGN = STATUS_SCREEN_SIM_TALLY_V_ALIGN + 8
STATUS_SCREEN_QUIT_V_ALIGN = STATUS_SCREEN_SIM_TALLY_V_ALIGN + 9
